# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

parameters:
- name: environment
  type: string
  default: prod
  values:
    - dev
    - prod


pool:
  name: Selfhosted

variables:
   - group: Terraform-prod


stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - checkout: self
            clean: true
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Terraform-connection'
              backendAzureRmResourceGroupName: 'project-twee'
              backendAzureRmStorageAccountName: 'projecttweesa'
              backendAzureRmContainerName: 'container-prod'
              backendAzureRmKey: 'prod.terraform.tfstate'
          - task: TerraformTask@5
            displayName: validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfdestroy
    dependsOn: tfvalidate
    condition: succeeded('tfvalidate')
    jobs:
      - deployment: destroy
        displayName: deploy destroy
        environment: prod
        strategy:
         runOnce:
           deploy:
             steps:
               - task: TerraformTask@5
                 inputs:
                   provider: 'azurerm'
                   command: 'init'
                   workingDirectory: '$(System.DefaultWorkingDirectory)/envs/prod'
                   backendServiceArm: 'Terraform-connection'
                   backendAzureRmResourceGroupName: 'project-twee'
                   backendAzureRmStorageAccountName: 'projecttweesa'
                   backendAzureRmContainerName: 'container-prod'
                   backendAzureRmKey: 'prod.terraform.tfstate'
               - task: DownloadSecureFile@1
                 name: tfvars
                 displayName: download tfvars
                 inputs:
                   secureFile: 'prod-terraform.tfvars'
               - task: TerraformTask@5
                 displayName: destroy
                 inputs:
                   provider: 'azurerm'
                   command: 'destroy'
                   workingDirectory: '$(System.DefaultWorkingDirectory)/envs/prod'
                   environmentServiceNameAzureRM: 'Terraform-connection'
                   commandOptions: '-var-file=$(tfvars.secureFilePath) -auto-approve'